[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama_web"
version = "1.0.0"
authors = [{name="eldablo23307"}]
dependencies = ["ollama", "flask"]

[project.scripts]
ollama-web = "ollama_web_eldablo23307.main:main"
